baseurl: "https://www.utam0k.jp/"
canonifyurls: true

DefaultContentLanguage: "ja"
hasCJKLanguage: true
title: "うたもく"
theme: utam0k
permalinks:
  post: /blog/:year/:month/:day/:contentbasename

MetaDataFormat: "yaml"
enableRobotsTXT: true

pagination:
  pagerSize: 30

disqusShortname: "utam0k"

pygmentsCodeFences: true
pygmentsUseClasses: true

summaryLength: 0

googleAnalytics: "UA-119773781-1"

languages:
  ja:
    weight: 1
    menu:
      main:
        - name: Posts
          url: /post/
          weight: 1
        - name: About
          url: /page/about/
          weight: 2
        - name: EN
          url: /en/
          weight: 3
        - name: Atom
          url: /index.xml
  en:
    title: utam0k
    weight: 2
    menu:
      main:
        - name: Posts
          url: /en/post/
          weight: 1
        - name: About
          url: /en/page/about/
          weight: 2
        - name: JP
          url: /
          weight: 3
        - name: Atom
          url: /en/index.xml

Params:
  description: "utam0k"
  shareTo: ["Twitter", "Hatena", "Facebook"]
  showFooterCredits: false
  twitter: utam0k
  useTwitterCard: true
  logo: img/logo.png
  comments: false
  author:
    name: Toru Komatsu
    twitter: utam0k
    github: utam0k

Author:
  name: Toru Komatsu
  email: k0ma@utam0k.jp
  twitter: utam0k
  github: utam0k

markup:
  goldmark:
    renderer:
      unsafe: true
