baseurl: "https://www.utam0k.jp/"
canonifyurls: true

DefaultContentLanguage: "ja"
hasCJKLanguage: true
title: "うたもく"
theme: utam0k
permalinks:
  post: /blog/:year/:month/:day/:contentbasename
  slides: /slides/:slug/

MetaDataFormat: "yaml"
enableRobotsTXT: true

pagination:
  pagerSize: 30

disqusShortname: "utam0k"

pygmentsCodeFences: true
pygmentsUseClasses: true

summaryLength: 0

services:
  googleAnalytics:
    ID: "G-F75YLEHSJN"

languages:
  ja:
    weight: 1
    menu:
      main:
        - name: Blog
          url: /blog/
          weight: 1
        - name: /tmp
          url: /tmp/
          weight: 2
        - name: Slides
          url: /slides/
          weight: 3
        - name: About
          url: /page/about/
          weight: 4
  en:
    title: utam0k
    weight: 2
    menu:
      main:
        - name: Blog
          url: /en/blog/
          weight: 1
        - name: /tmp
          url: /en/tmp/
          weight: 2
        - name: Slides
          url: /en/slides/
          weight: 3
        - name: About
          url: /en/page/about/
          weight: 4

Params:
  description: "utam0k"
  shareTo: ["Twitter", "Hatena", "Facebook"]
  showFooterCredits: false
  twitter: utam0k
  useTwitterCard: true
  logo: img/logo.png
  comments: false
  author:
    name: Toru Komatsu
    twitter: utam0k
    github: utam0k

Author:
  name: Toru Komatsu
  email: k0ma@utam0k.jp
  twitter: utam0k
  github: utam0k

markup:
  goldmark:
    renderer:
      unsafe: true
    parser:
      attribute:
        block: true
      autoHeadingIDType: github
    extensions:
      alert:
        enable: true
      typographer:
        disable: true
  tableOfContents:
    startLevel: 1
    endLevel: 5
    ordered: false
